
# Theme Settings
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

remote_theme: VSecDK/minimal-mistakes-theme
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "VSec"
title_separator          : "-"
subtitle                 : Security Community
name                     : "VSec"
email                    : "VSec-Community@protonmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  VSec is a danish non-profit InfoSec community that are trying to “unify”
  the different local infosec groups in Denmark by providing a shared communication platform. 
  VSec is meant to be a community for the community by the community.
twitter_username: VSecDK
github_username: VSecDK
search: true

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Copenhagen

include:
  - _pages
  - .well-known

exclude:
 - _profiles/0_template.md

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/VSecDK"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/VSecDK"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCGQCK473y181BjNMJLrW11g"


# Collections
collections:
  profiles:  # Blank to initialize

# Set Theme Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false

# Use Liquid Archives for categories/tags
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
